### ISSUE TITLE
Crash on Coffee Minigame

### ISSUE THREAD

**Issue by TULOA** [usineur/Zelda3T#7] opened 2018-06-19 02:21 UTC
After arriving in town as a bunny I have been getting game crashes after running the conveyor belt and pushing the button then talking to the guy. Not sure if its something related to my save or not.

Attached should be a save just before doing the minigame.
[3t1.zip](https://github.com/usineur/Zelda3T/files/2113602/3t1.zip)

Later on I can add the dump file if needed.

Using 3.60 Henkaku with no other mods.

I had to export to and use PC to pass this part.

**Comment by usineur** [comment] 2018-06-19 20:59
Fixed with commit c455ea

Thanks to @NicolasR 

I will make a new release asap, for now, you can replace your current eboot.bin in ux0:app/ZELDATTT1/ with [this one](https://www.ferb.fr/vita/eboot.bin)

**Comment by usineur** [comment] 2018-06-21 18:49
Ok, the dump points the problem in `chercheText` function as @NicolasR pointed me.

I'm thinking of rewriting this function without recursive calls, with a "completed" token or something like that.

I will see that this week-end if i'm able to find some time.

**Comment by usineur** [comment] 2018-06-21 18:54
Also, can you provide me as many saves as possible, where you encounter game crashes, with a short describe, to explain me how to reproduce the crash quickly.

**Comment by TULOA** [comment] 2018-06-21 20:17
Sure,

Ocarina Crash:
Go into the temple and get the song of soaring in the northmost room.
Exit and attempt to play the ocarina.
Will crash on attempt.
Save: [Ocarina Crash Savepoint.zip](https://github.com/usineur/Zelda3T/files/2125199/Ocarina.Crash.Savepoint.zip)

Will edit with the Trading save in a bit. Otherwise with my file go to the past era of Mabe Village and talk to the power gem trader and it will crash with that save also.

**Comment by usineur** [comment] 2018-06-21 20:59
Same saves. "Trading Crash Savepoint.zip" is the "ocarina" save too.

**Comment by usineur** [comment] 2018-06-21 21:58
Could you please try this [eboot.bin](https://www.ferb.fr/vita/eboot.bin) ?

 I will push my changes if everything seems ok.

**Comment by usineur** [comment] 2018-06-22 07:31
Ok, thanks for your feedback, my changes are pushed.

I will leave this issue open for a while, until we can say with certitude that problems linked to `chercheText `function are definitely fixed.

**Comment by NicolasR** [comment] 2018-06-22 07:54
I will do more tests too with your version.

Very strange this problem. I would like to know what is the real vita limitation.

**Comment by usineur** [comment] 2018-07-10 21:07
So, has one of you finish the game ? No more crashes ?

If so, I think it's time to make a new release

**Comment by NicolasR** [comment] 2018-07-15 10:53
I was able to finish the main quest (but I didn't restart a full save).
Found that it's not possible to finish secondary quest Casino because of Vita stick mapping but it's not related to this issue.

**Comment by usineur** [comment] 2018-07-17 09:23
If you find a way to fix this quest, do not hesitate to make a PR. I will wait a bit for it before releasing a new version.

I close.

**Closed by usineur** 2018-07-17 09:23 UTC
